version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17 # Use the desired Java runtime version (e.g., corretto17)
  pre_build:
    commands:
      - echo "Pre-build phase"
      # Add any pre-build commands here, e.g., installing dependencies
  build:
    commands:
      - echo "Build phase"
      - ./gradlew build # Use the appropriate build command for your Java project
  post_build:
    commands:
      - echo "Post-build phase"
      # Add any post-build commands here, e.g., running tests
artifacts:
  files:
    - build/libs/* # Adjust the path to your Lambda deployment package
    - appspec.yml
  discard-paths: yes
cache:
  paths:
    - '/root/.gradle/caches'