AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions.

Resources:
  # Details about the myDateTimeFunction Lambda function
  KuberTrailerLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: KuberTrailerLambda
      Handler: com.kuber.trailer.lambda.LambdaProxy::handleRequest
      Runtime: java17
      # Instructs your myDateTimeFunction is published to an alias named "live".
      AutoPublishAlias: live
      CodeUri: build/distributions/KuberTrailerLambda.zip
      Timeout: 60
      MemorySize: 512
      DeploymentPreference:
        Type: AllAtOnce
      # Grants this function permission to call lambda:InvokeFunction
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "lambda:InvokeFunction"
              Resource: '*'


